// Fake catalog data standing in for the DuckDB-backed API (hub_data.py / api.py)
// in the source app. Shapes mirror schema.py's DatasetMeta exactly.
// Plain globals (no ES module export) so a bundler-less <script src> works.
window.MOCK = {};
window.MOCK.STATS = { n_datasets: 128, n_episodes: 46920, n_frames: 8412300 };

window.MOCK.FACETS = {
  embodiments: ["single_arm", "bimanual", "humanoid", "mobile", "quadruped"],
  formats: ["lerobot_v3", "rlds", "hdf5", "mcap"],
  provenances: ["teleop", "kinesthetic", "sim", "autonomous", "human_video"],
  concepts: [
    { id: "pick_place", label: "抓取放置 / Pick & Place" },
    { id: "insertion", label: "插入装配 / Insertion" },
    { id: "pushing", label: "推动 / Pushing" },
    { id: "folding", label: "折叠 / Folding" },
    { id: "opening", label: "开启 / Opening" },
    { id: "stacking", label: "堆叠 / Stacking" },
  ],
};

window.MOCK.DATASETS = [
  {
    dataset_id: "lerobot/aloha_sim_insertion_human",
    name: "ALOHA Sim Insertion",
    embodiment: "bimanual",
    source_format: "lerobot_v3",
    commercial_ok: true,
    n_episodes: 400,
    quality_score: 0.91,
    has_failure_labels: true,
    license_spdx: "apache-2.0",
    provenance_type: "teleop",
    source: "huggingface",
    quality_tier: "deep",
    action_convention: { space: "joint", frame: "base", abs_or_delta: "delta", units: "rad" },
    tasks: ["插入装配"],
    scenes: ["桌面"],
    modalities: ["彩色图像", "本体状态"],
    homepage: "https://huggingface.co/datasets/lerobot/aloha_sim_insertion_human",
  },
  {
    dataset_id: "lerobot/pusht",
    name: "PushT",
    embodiment: "single_arm",
    source_format: "lerobot_v3",
    commercial_ok: false,
    n_episodes: 206,
    quality_score: 0.74,
    has_failure_labels: false,
    license_spdx: "cc-by-nc-sa-4.0",
    provenance_type: "teleop",
    source: "huggingface",
    quality_tier: "metadata",
    action_convention: { space: "end_effector", frame: "world", abs_or_delta: "abs", units: "m" },
    tasks: ["推动"],
    scenes: ["桌面"],
    modalities: ["彩色图像", "本体状态"],
    homepage: "https://huggingface.co/datasets/lerobot/pusht",
  },
  {
    dataset_id: "openx/fractal20220817_data",
    name: "Fractal (RT-1)",
    embodiment: "single_arm",
    source_format: "rlds",
    commercial_ok: true,
    n_episodes: 87212,
    quality_score: 0.68,
    has_failure_labels: false,
    license_spdx: "apache-2.0",
    provenance_type: "teleop",
    source: "openx",
    quality_tier: "metadata",
    action_convention: { space: "end_effector", frame: "base", abs_or_delta: "delta", units: "m" },
    tasks: ["抓取放置", "开启"],
    scenes: ["厨房", "办公室"],
    modalities: ["彩色图像", "语言"],
    homepage: "https://robotics-transformer1.github.io/",
  },
  {
    dataset_id: "agibot/agibot_world_beta",
    name: "AgiBot World (beta)",
    embodiment: "humanoid",
    source_format: "hdf5",
    commercial_ok: true,
    n_episodes: 8500,
    quality_score: 0.83,
    has_failure_labels: true,
    license_spdx: "cc-by-4.0",
    provenance_type: "teleop",
    source: "agibot",
    quality_tier: "deep",
    action_convention: { space: "joint", frame: "base", abs_or_delta: "abs", units: "rad" },
    tasks: ["堆叠", "折叠", "插入装配"],
    scenes: ["家庭", "工厂制造"],
    modalities: ["彩色图像", "深度", "本体状态", "语言"],
    homepage: "https://agibot-world.com/",
  },
  {
    dataset_id: "robomind/mobile_manip_v2",
    name: "RoboMind Mobile Manip v2",
    embodiment: "mobile",
    source_format: "mcap",
    commercial_ok: false,
    n_episodes: 1120,
    quality_score: 0.55,
    has_failure_labels: true,
    license_spdx: "cc-by-nc-4.0",
    provenance_type: "autonomous",
    source: "robomind",
    quality_tier: "metadata",
    action_convention: { space: "base_velocity", frame: "world", abs_or_delta: "delta", units: "m/s" },
    tasks: ["导航", "抓取放置"],
    scenes: ["商业场所"],
    modalities: ["彩色图像", "本体状态"],
    homepage: "",
  },
  {
    dataset_id: "unitree/quadruped_terrain",
    name: "Quadruped Terrain Traversal",
    embodiment: "quadruped",
    source_format: "rlds",
    commercial_ok: true,
    n_episodes: 3040,
    quality_score: 0.79,
    has_failure_labels: false,
    license_spdx: "apache-2.0",
    provenance_type: "sim",
    source: "unitree",
    quality_tier: "metadata",
    action_convention: { space: "joint", frame: "base", abs_or_delta: "delta", units: "rad" },
    tasks: ["导航"],
    scenes: ["工厂制造"],
    modalities: ["本体状态", "触觉力觉"],
    homepage: "",
  },
];

window.MOCK.COVERAGE_CELLS = [
  { embodiment: "single_arm", concept: "pick_place", count: 42 },
  { embodiment: "single_arm", concept: "pushing", count: 18 },
  { embodiment: "single_arm", concept: "opening", count: 6 },
  { embodiment: "bimanual", concept: "insertion", count: 31 },
  { embodiment: "bimanual", concept: "folding", count: 9 },
  { embodiment: "bimanual", concept: "stacking", count: 4 },
  { embodiment: "humanoid", concept: "stacking", count: 12 },
  { embodiment: "humanoid", concept: "folding", count: 7 },
  { embodiment: "mobile", concept: "pick_place", count: 3 },
  { embodiment: "quadruped", concept: "pick_place", count: 0 },
];
